spring:
  datasource:
    url: jdbc:h2:mem:testdb

  sql:
    init:
      mode: always
  #      data-locations: data.sql
  #      schema-locations: schema.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

  logging:
    level:
      ROOT: ERROR

resilience4j.bulkhead:
  instances:
    authorService:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 1
    userService:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 1
    bookService:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 1
    commentService:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 1
    genreService:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 1

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 5
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10